### ISSUE TITLE
Indexing symbol packages and URL for Symbol file locations in Visual Studio

### ISSUE THREAD

**Issue by varbedi** [SymbolSource/SymbolSource#18]
Hi,

I am currently testing SymbolSource on localhost at - https://localhost/SymbolSource.Server/

I can push the packages using source URL - https://localhost/SymbolSource.Server/api/v2/package

Pushing packages created some folder and files. The nupkg files names had some Guid value and running 'nuget list -prerelease -allversions -source https://localhost/SymbolSource.Server/,all,new' gave me result as:

47bdf8da-30d3-4bc1-b3bc-8eb2019f0fd9 1.0.0-unknown
c7a283fb-ea53-4344-8a7c-6c331a8a402a 1.0.0-unknown
ded1f2b2-6e08-44dd-9d7b-eb6e0f34a738 1.0.0-unknown

Based on #1 , it seemed like I needed to run SymbolSource.Processor.Console. I set the FileStorage.RootPath, PackageProcessor.ServerUrl and PackageProcessor.BatchSize before running the console app. After that, running the nuget list command 'nuget list -prerelease -allversions -source https://localhost/SymbolSource.Server/,all,original' gave me the result as:

AssemblyNameRemoved1 1.5.0-at-2ECAMH
AssemblyNameRemoved2 1.5.0-at-2ECAMH
AssemblyNameRemoved3 1.18.0-at-2ECAMH

I have purposely removed the assembly names here. Can you please let me know what I need to do so they get indexed successfully? If there is any documentation, can you please point me to that?

Can you also please confirm the final URL I can use in Visual Studio to add the symbol file location?

Will I have to run the SymbolSource.Processor.Console everytime a new symbols package is pushed?

**Comment by varbedi** [comment]
Hi,

I tried running the console application again with newly uploaded package and noticed that I get an error as:

 Error while indexing package AssemblyNameRemoved/1.18.0-at-2EGCMR:
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
   at SymbolSource.Processor.Legacy.SymbolStoreManager.ReadHashInternal(String pdbFileHash) in SymbolSource.Processor\Legacy\SymbolStoreManager.cs:line 28
   at SymbolSource.Processor.Legacy.StreamExtensions.Execute[T](Stream stream, Func`2 action, String fileName) in SymbolSource.Processor\Legacy\StreamExtensions.cs:line 43
   at SymbolSource.Processor.Legacy.StreamExtensions.Execute[T](Stream stream, Func`2 action) in SymbolSource.Processor\Legacy\StreamExtensions.cs:line 30
   at SymbolSource.Processor.Legacy.SymbolStoreManager.ReadHash(Stream stream) in SymbolSource.Processor\Legacy\SymbolStoreManager.cs:line 12
   at SymbolSource.Processor.Legacy.Projects.AddInfoBuilder.BuildBinaryInfo(IList`1 fileInfos, IPackageEntry binaryFileInfo) in SymbolSource.Processor\Legacy\Projects\AddInfoBuilder.cs:line 66
   at SymbolSource.Processor.Legacy.Projects.AddInfoBuilder.<>c__DisplayClass4_0.<Build>b__1(IPackageEntry b) in SymbolSource.Processor\Legacy\Projects\AddInfoBuilder.cs:line 29
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at SymbolSource.Processor.Processor.PackageTask.<ProcessThrottled>d__7`2.MoveNext() in SymbolSource.Processor\Processor\PackageTask.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SymbolSource.Processor.Processor.IndexPackageTask.<IndexPackage>d__7.MoveNext()


Has anyone else encountered the same issue?

Thanks,
